<?php
/**
 * Block asset registration.
 *
 * @package WPFormsBlocks
 */

defined( 'ABSPATH' ) || exit;

/**
 * Load an asset manifest generated by @wordpress/scripts.
 *
 * @param string $name Build entry name.
 * @return array{dependencies: array<int, string>, version: string}
 */
function formblox_get_asset( $name ) {
	$asset_file = FORMBLOX_DIR . 'build/' . $name . '.asset.php';

	if ( file_exists( $asset_file ) ) {
		$asset = require $asset_file;
		if ( is_array( $asset ) ) {
			return wp_parse_args(
				$asset,
				array(
					'dependencies' => array(),
					'version'      => FORMBLOX_VERSION,
				)
			);
		}
	}

	return array(
		'dependencies' => array(),
		'version'      => FORMBLOX_VERSION,
	);
}

/**
 * Register the shared editor and front-end assets named in block.json.
 *
 * @return void
 */
function formblox_register_assets() {
	$editor_asset = formblox_get_asset( 'index' );
	$style_asset  = formblox_get_asset( 'style' );
	$view_asset   = formblox_get_asset( 'view' );

	wp_register_script(
		'wp-forms-blocks-editor',
		FORMBLOX_URL . 'build/index.js',
		$editor_asset['dependencies'],
		$editor_asset['version'],
		true
	);
	wp_set_script_translations(
		'wp-forms-blocks-editor',
		'wp-forms-blocks',
		FORMBLOX_DIR . 'languages'
	);

	wp_register_style(
		'wp-forms-blocks-editor',
		FORMBLOX_URL . 'build/index.css',
		array(),
		$editor_asset['version']
	);

	wp_register_style(
		'wp-block-formblox-form-input',
		FORMBLOX_URL . 'build/style.css',
		array(),
		$style_asset['version']
	);

	wp_register_style(
		'wp-block-formblox-form-submit-button',
		FORMBLOX_URL . 'build/style.css',
		array(),
		$style_asset['version']
	);

	if (
		function_exists( 'wp_register_script_module' ) &&
		null === wp_script_modules()->get_registered( '@formblox/form/view' )
	) {
		wp_register_script_module(
			'@formblox/form/view',
			FORMBLOX_URL . 'build/view.js',
			$view_asset['dependencies'],
			$view_asset['version']
		);
	}
}

/**
 * Enqueue the consolidated equivalents of Gutenberg's block-library editor assets.
 *
 * @return void
 */
function formblox_enqueue_editor_assets() {
	wp_enqueue_script( 'wp-forms-blocks-editor' );
	wp_enqueue_style( 'wp-forms-blocks-editor' );
}
