<?php
/**
 * Block asset registration.
 *
 * @package WPFormsBlocks
 */

defined( 'ABSPATH' ) || exit;

/**
 * Load an asset manifest generated by @wordpress/scripts.
 *
 * @param string $name Build entry name.
 * @return array{dependencies: array, version: string}
 */
function wp_forms_blocks_get_asset( $name ) {
	$asset_file = WP_FORMS_BLOCKS_DIR . 'build/' . $name . '.asset.php';

	if ( file_exists( $asset_file ) ) {
		$asset = require $asset_file;
		if ( is_array( $asset ) ) {
			return wp_parse_args(
				$asset,
				array(
					'dependencies' => array(),
					'version'      => WP_FORMS_BLOCKS_VERSION,
				)
			);
		}
	}

	return array(
		'dependencies' => array(),
		'version'      => WP_FORMS_BLOCKS_VERSION,
	);
}

/**
 * Register the shared editor and front-end assets named in block.json.
 */
function wp_forms_blocks_register_assets() {
	$editor_asset = wp_forms_blocks_get_asset( 'index' );
	$view_asset   = wp_forms_blocks_get_asset( 'view' );

	wp_register_script(
		'wp-forms-blocks-editor',
		WP_FORMS_BLOCKS_URL . 'build/index.js',
		$editor_asset['dependencies'],
		$editor_asset['version'],
		true
	);

	wp_set_script_translations(
		'wp-forms-blocks-editor',
		'wp-forms-blocks',
		WP_FORMS_BLOCKS_DIR . 'languages'
	);

	wp_register_style(
		'wp-forms-blocks-editor',
		WP_FORMS_BLOCKS_URL . 'build/index.css',
		array(),
		$editor_asset['version']
	);

	wp_register_style(
		'wp-forms-blocks',
		WP_FORMS_BLOCKS_URL . 'build/style.css',
		array(),
		$editor_asset['version']
	);

	if ( function_exists( 'wp_register_script_module' ) ) {
		wp_register_script_module(
			'wp-forms-blocks-view',
			WP_FORMS_BLOCKS_URL . 'build/view.js',
			$view_asset['dependencies'],
			$view_asset['version']
		);
	}
}
