<?php
/**
 * KSES support for form controls saved by the blocks.
 *
 * @package WPFormsBlocks
 */

defined( 'ABSPATH' ) || exit;

/**
 * Allow the form-control elements and attributes generated by this plugin.
 *
 * @param array[] $tags    Allowed HTML tags.
 * @param string  $context KSES context.
 * @return array[]
 */
function wp_forms_blocks_kses_allowed_html( $tags, $context ) {
	if ( 'post' !== $context ) {
		return $tags;
	}

	$tags['input']    = array_merge(
		isset( $tags['input'] ) ? $tags['input'] : array(),
		array(
			'aria-required' => true,
			'autocomplete'  => true,
			'checked'       => true,
			'class'         => true,
			'disabled'      => true,
			'id'            => true,
			'name'          => true,
			'placeholder'   => true,
			'required'      => true,
			'style'         => true,
			'tabindex'      => true,
			'type'          => true,
			'value'         => true,
		)
	);
	$tags['label']    = array_merge(
		isset( $tags['label'] ) ? $tags['label'] : array(),
		array(
			'class' => true,
			'for'   => true,
			'style' => true,
		)
	);
	$tags['textarea'] = array_merge(
		isset( $tags['textarea'] ) ? $tags['textarea'] : array(),
		array(
			'aria-required' => true,
			'class'         => true,
			'id'            => true,
			'name'          => true,
			'placeholder'   => true,
			'required'      => true,
			'style'         => true,
		)
	);

	return $tags;
}
